spring.application.name=cards-limit-service

spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.url=jdbc:postgresql://localhost:5433/limit_db

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Default Limits Configuration
app.default-limits.withdrawal-limit=withdrawal-limit
app.default-limits.transfer-limit=transfer-limit

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.file.name=logs/app.log

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

# kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
spring.kafka.consumer.group-id=cards-limit-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.UUIDDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=event-dto:kg.bakaibank.cardslimitservice.outbox.event.OutboxEvent
kafka.topic.payments=payments-topic