spring.application.name=cards-limit-service

spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.url=jdbc:postgresql://localhost:5433/limit_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Default Limits Configuration
app.default-limits.withdrawal-limit=withdrawal-limit
app.default-limits.transfer-limit=transfer-limit

#Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.file.name=logs/app.log

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB