spring.application.name=cards-limit-service

spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.url=jdbc:postgresql://localhost:5433/limit_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Default Limits Configuration
app.default-limits.cash-in=default-cashin
app.default-limits.cash-out=default-cashout